const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const CHANGE_LOGIN = 'CHANGE_LOGIN';
const LOAD_COMMENTS = 'LOAD_COMMENTS';
const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
const SHOW_MESSAGE = 'SHOW_MESSAGE';

export { CHANGE_LANGUAGE, CHANGE_LOGIN, LOAD_COMMENTS, CLEAN_MESSAGE, SHOW_MESSAGE }